name: C/C++ CI

on:
  push:
    branches: [ mrmc-release_3.9.6 ]
  pull_request:
    branches: [ mrmc-release_3.9.6 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up sdk
      run: |
         sudo apt-get update && sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev
         sudo apt-get install build-essential git curl libcurl4-openssl-dev autoconf \
         unzip zip zlib1g-dev gawk gperf cmake
         mkdir /opt/android-sdk-linux
         cd /opt/android-sdk-linux
         wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip
         unzip commandlinetools-linux-6200805_latest.zip
         cd tools/bin
         echo "y" | ./sdkmanager  platform-tools --sdk_root=/opt/android-sdk-linux
         ./sdkmanager  "platforms;android-26" --sdk_root=/opt/android-sdk-linux
         ./sdkmanager "build-tools;26.0.2" --sdk_root=/opt/android-sdk-linux
         ./sdkmanager "cmake;3.6.4111459" --sdk_root=/opt/android-sdk-linux
         ./sdkmanager tools --sdk_root=/opt/android-sdk-linux
    - name: Set up NDK
      run: |
         cd /opt
         wget https://dl.google.com/android/repository/android-ndk-r20b-linux-x86_64.zip
         unzip android-ndk-r20b-linux-x86_64.zip
    - name: Issue key
      run: |
         keytool -genkey -keystore $GITHUB_WORKSPACE/MrMC.keystore -v -alias \
         androiddebugkey -dname "CN=Android Debug,O=Android,C=US" -keypass \
         android -storepass android -keyalg RSA -keysize 2048 -validity 10000
    - name: make dep
      run: |
         cd $GITHUB_WORKSPACE/tools/depends
         ./bootstrap
         ./configure --with-tarballs=/opt/xbmc-tarballs --host=arm-linux-androideabi --with-sdk-path=/opt/android-sdk-linux --with-sdk=android-21 --with-ndk-path=/opt/android-ndk-r20b --with-ndk-api=21 --prefix=/opt/xbmc-depends
         make -j8
    - name: make apk
      run: |
         cd $GITHUB_WORKSPACE
         make -C tools/depends/target/xbmc
         make
         make apk
         
           
